### ISSUE TITLE
Kingdom

### ISSUE THREAD

**Issue by B1gLev** [B1gLev/TryWillon#1]
Fordítások nincsenek teljesen készen(90% kész), invade parancs sem működik valami fényesen.

**Comment by B1gLev** [comment]
Hamarosan új kingdom verzió!

**Comment by B1gLev** [comment]
Az új verzió tesztelés alatt!

**Comment by B1gLev** [comment]
> Az új verzió tesztelés alatt!

Betöltési hiba, fejlesztő dolgozik rajta.

**Comment by TheKr1szTEN** [comment]
Kingdoms fordítás 99%-a készen van. 
Gazdasági opciók lefordítva, beállítása még nincs kész.
