### ISSUE TITLE
Bug-Jelentés

### ISSUE THREAD

**Issue by Jaffis** [B1gLev/TryWillon#10]
Hali, Jaffis vagyok, egy mostani építészetek. A bug röviden, hogyha beleállsz a komposztálóba, és magamra húzok egy pistont fentről egy bányában, akkor az x-ray-ként működik... Látod a mobokat, a lávát, a szobákat, a lávát, stb.

**Comment by B1gLev** [comment]
Megpróbáljuk orvosolni, de szerintem ezt nem nagyon lehet
