### ISSUE TITLE
"elégtek" a cuccaim.

### ISSUE THREAD

**Issue by Milka29** [B1gLev/TryWillon#13]
mikor kidobott a szerver, pont elkezdett rám folyni a láva a netherben, és mikor visszatudtam menni, csak a halál képernyőt láttam,  és nem volt ott semmi cuccom, (pedig netherite-ból voltak, és az nem ég el a lávában). mit lehetne tenni?

**Comment by TheKr1szTEN** [comment]
Kérlek sorold fel azokat a tárgyakat amik "elégtek"

**Comment by Milka29** [comment]
Netjerite spapka, Enchantjai: védelem 4,  törhetetlenség 3, önjavítás, aqua affinity Gyémátmellvértes elytra, Enchantjai: véd 4, tör 3, önjavítás.Netherite nadrág,Enchantjai: véd 4, tör 3, önjavításNetherite cipő,Enchantjai: véd 4, tör 3, önjavítás, mélyjárás 3, könnyűesés 4.Netjerite kard,Enchantjai: lángpallos 2, tör 3, önjavítás, élesség 5, zsákmányolás 3, suhintás 32 darab netherite csákány,1. Enchantjai: Tör 3, hatékonyság 5, szerencse 3, önjavítás2. Enchantjai: Tör 3, hatékonyság 5, gyengédérintés, önjavításNetherite balta,Enchantjai: Hatékonyság 5, tör 3, önjavítás, szerencse 3Netherite ásóEnchantjai: hatékonyság  5,  törhetetlenség 3, önkavítás, gyengéd érintés,10 aranyalma1 arany cipő3 ellenszer64 nyílÍj,Enchantjai: végtelen, , ütés 2, erő 5,  tör 3, lángPajzs: Enchantjai: tör 3, önjavításSzámszeríj: Enchatjai: piercing 4, önjavítás, tör 3, quick charge 3,1 Életmentés toteme-------- Eredeti üzenet --------Feladó: TheKr1szTEN <notifications@github.com>Dátum: 2020. aug. 30., V 12:43Címzett: B1gLev/TryWillon <TryWillon@noreply.github.com>Másolatot kap: Milka29 <valamivalaki753@gmail.com>, Author <author@noreply.github.com>Tárgy: Re: [B1gLev/TryWillon] "elégtek" a cuccaim. (#13)

Kérlek sorold fel azokat a tárgyakat amik "elégtek"

**Comment by TheKr1szTEN** [comment]
Minden tárgy vissza lett adva, a témát lezárom.
