### ISSUE TITLE
Falusi

### ISSUE THREAD

**Issue by Milka29** [B1gLev/TryWillon#21]
Amikor petnek állítottam be az 1 smaragdért áruló, önjavításos falusit akkor mikor "elengedtem"  3x adta drágábban  azt az  önjavításos könyvet az eredeti árhoz képest.

**Comment by B1gLev** [comment]
(Gonosz a falusi) komolyabbra véve nem tudom mitől lehet ez, de nem mondanám hibának sem. Nem feltétlenül fogod azt a falusit ugyan úgy megkapni szerintem. De tegyük hozzá, hogy ez beta build plugin.

**Comment by Redhun2** [comment]
azért adta ilyen drágán mert szét verted a fejét és ha megütöd MINDENT drágábban ad
