### ISSUE TITLE
Halál

### ISSUE THREAD

**Issue by Milka29** [B1gLev/TryWillon#23]
Arra jöttem fel a szerverre hogy halott vagyok..

**Comment by TheKr1szTEN** [comment]
Hol voltál, mit csináltál mielőtt leléptél? Bővítsd kérlek az infót.

**Comment by Milka29** [comment]
Királyságomban léptem ki ha minden igaz. Megöltem pár mobot aztán kiléptem.

TheKr1szTEN <notifications@github.com> ezt írta (időpont: 2020. szept. 15.,
K 17:13):

**Comment by TheKr1szTEN** [comment]
Tudsz mondani egy időpontot kb, hogy mikor léptél ki és mikor léptél be (amikor meghaltál)?
Nem kell percre pontosan, de azért valamennyire pontos legyen

**Comment by Milka29** [comment]
Amikor kiléptem az úgy szerintem tegnap 18 óra körül lehetett. Ma mikor
beléptem az úgy 16 óra 50 körül lehetett.

TheKr1szTEN <notifications@github.com> ezt írta (időpont: 2020. szept. 15.,
K 17:18):

**Comment by TheKr1szTEN** [comment]
Utána nézek, köszi!

**Comment by Milka29** [comment]
Én köszönöm.

TheKr1szTEN <notifications@github.com> ezt írta (időpont: 2020. szept. 15.,
K 17:27):

**Comment by TheKr1szTEN** [comment]
Valószínű amikor leléptél a szerverről, nem volt/kevés hp-d volt. Bejelentkezési időtúllépés is volt, melyet a vízben töltöttél, így fulladás következett be. Az elveszett raktárad vissza adtam. 
Halál pozíciója - 7309.025791188755, 62.1147690839767, 4834.1722349622
Halál ideje - 2020. 09. 15. 16:29:48
