### ISSUE TITLE
Elveszett cuccok az ec-ből

### ISSUE THREAD

**Issue by SzokeMartin** [B1gLev/TryWillon#27]
Amint tudjátok eltűntek az enderládámból a harcos cuccaim nagyon hosszú listát kellene írnom hogy mindet vissza tudjátok adni, tudom sok dolgotok van, nem csak az én bajom de nekem fontosak a cuccok, sok időt költöttem rájuk.

**Comment by TheKr1szTEN** [comment]
A hibajegyhez nem csatoltál semmilyen bizonyító képet, így nem tudunk semmit sem csinálni ezzel. 
Ha ilyen probléma lesz a jövőben, akkor nem lesz szükség hibajegy nyitásra, mivel vissza tudjuk nézni.

**Comment by TheKr1szTEN** [comment]
Mivel a hibajegyhez még nem érkezett kép, lezárom.
