### ISSUE TITLE
kifagytam

### ISSUE THREAD

**Issue by Milka29** [B1gLev/TryWillon#29]
egy faluban megtámadott  egy vasgólem kifagytam és kidobott amikor visszajöttem akkor nem voltak meg a cuccaim mert meghaltam. A /back a spawnra dobott.

**Comment by TheKr1szTEN** [comment]
Ez a kifagyás milyen okból történt? Game crash, vagy esetleg szerver lag?

**Comment by Milka29** [comment]
szerintem szerverlagg de csak én voltam a szerveren.

**Comment by TheKr1szTEN** [comment]
Ezesetben kérnék egy időpontot, lecsekkolom. Ha önhibából történt akkor sajnos nem tudok mit tenni.

**Comment by Milka29** [comment]
kb 17:38-kor

**Comment by TheKr1szTEN** [comment]
A grafikonok szerint minden rendben volt.
Valószínűleg game crash okozhatta a gondokat.
