### ISSUE TITLE
Vérszett! 

### ISSUE THREAD

**Issue by SzokeMartin** [B1gLev/TryWillon#30]
Kinyitottam egy vérszett darabot, azaz egy mellvértet és nem kaptam meg. Meg az esélyek nagyon rosszak. A 20 ból csak a 11. Re nyitottam valamit.

**Comment by TheKr1szTEN** [comment]
Üdv!
Mivel egy ritka szettről van szó, így a logika szerint nem lehet 2 kulcsból kinyitni akármit.
Az elveszett cuccot intézem.
