### ISSUE TITLE
Spawner problémák. 

### ISSUE THREAD

**Issue by SzokeMartin** [B1gLev/TryWillon#31]
A spawneres xp farmot éppen szedtem szét, mikor arra lettem figyelmes hogy 6 spawnerből malac spawner lett és ha jól emlékszem 3 skeleton és 3 zombie spawner volt. A beváltását kérném.

**Comment by TheKr1szTEN** [comment]
Üdv!
Hol vannak ezek a malac spawnerek?
Írj majd discordon ha fent vagy és elintézzük.
