### ISSUE TITLE
[B1gLev/TryWillon] 

### ISSUE THREAD

**Issue by PDF10** [B1gLev/TryWillon#32]
Amikor a szerver leállt és újra lett indítva elvesztek ezek a cuccaim: 1db creeper pet
                                                                                                            64db puskapor
                                                                                                            1db soulbound rune

**Comment by TheKr1szTEN** [comment]
Hogy történt?
Hol voltak leállás előtt a tárgyak?

**Comment by PDF10** [comment]
az inventory-ban

**Comment by TheKr1szTEN** [comment]
Leállás előtt raktad bele az inventoryba?

**Comment by PDF10** [comment]
Igen mármint onnan pakoltam pont ki de nem ezeket

**Comment by TheKr1szTEN** [comment]
Hová pakoltad ki?

**Comment by PDF10** [comment]
egy ládába a slimefun részlegemen

**Comment by TheKr1szTEN** [comment]
Ott megnézted? Enderchestekben, stb?

**Comment by PDF10** [comment]
igen és nem voltak ott de pár dolgom megduplázodott

**Comment by TheKr1szTEN** [comment]
Mi duplázódott meg?

**Comment by PDF10** [comment]
a 64db puskaporból 64db izzókőpor lett, a soulbound rune-ból Earth rune-a lett, a creeper pet-ból pedig slime pet lett.

**Comment by TheKr1szTEN** [comment]
Utána nézek.

**Comment by PDF10** [comment]
Rendben

**Comment by TheKr1szTEN** [comment]
A tárgyakat visszaadtam.
További jó játékot!
