### ISSUE TITLE
B1gLev/TryWillon

### ISSUE THREAD

**Issue by PDF10** [B1gLev/TryWillon#33]
Chimpy buggal kilopta az inventory-mból az összes értékemet

**Comment by B1gLev** [comment]
Hogyan mi történt?

**Comment by PDF10** [comment]
a pusztakezek elvileg úgy müködnek hogy ha a kezedben van valami az kitudják lopni. Úgye?

**Comment by B1gLev** [comment]
Nem tudok róla, hogy lenne benn bármi ilyesmi de megnézem.

**Comment by PDF10** [comment]
kösz

**Comment by PDF10** [comment]
Venci és a többiek buggolt szeteket dobtak ki a barátomnak darner-nek. olyan cuccok hogy (szó szerint törhetetlen).

**Comment by B1gLev** [comment]
Képet tudsz küldeni?

**Comment by PDF10** [comment]
visszalopták venciék

**Comment by B1gLev** [comment]
Lehetséges, hogy puszta kezekkel ha megutnak ki esik a kezedből az item

**Comment by PDF10** [comment]
okéé. Csak hogy nem volt a kezemben.

**Comment by B1gLev** [comment]
Érdekes akkor

**Comment by B1gLev** [comment]
Jaj lezártam xd

**Comment by PDF10** [comment]
megkérdeztem hogyan és annyit válaszolt "magic"

**Comment by B1gLev** [comment]
Akkor tehát nem volt semmi a kezedben ugye?

**Comment by PDF10** [comment]
semmi max a rohathús amit kajaként használok

**Comment by B1gLev** [comment]
Táskában voltak az ércek?

**Comment by PDF10** [comment]
milyen ércek?

**Comment by PDF10** [comment]
az összes cuccom

**Comment by B1gLev** [comment]
Kezedben volt táska?

**Comment by PDF10** [comment]
kezembe vettem aztán átváltottam üres szlotra megütött és kidrop-olta

**Comment by B1gLev** [comment]
Valoszinuleg úgy érezte, hogy ,még ott van és kész. Ezzel en nem tudunk mit csinálni.

**Comment by PDF10** [comment]
buggolt a szerver?

**Comment by PDF10** [comment]
amúgy a log nem müködik mindig
