### ISSUE TITLE
Nether portál

### ISSUE THREAD

**Issue by Adam0619** [B1gLev/TryWillon#34]
Beszorultunk egy nether portálba egy másik nemzet területén, az effekt miatt a chatet sem tudjuk használni hogy el tpzzünk, viszont vissza sem visz a netherbe.

**Comment by TheKr1szTEN** [comment]
Mi a játékosnved?

**Comment by TheKr1szTEN** [comment]
Probléma megoldva, a hibajegy lezárásra kerül.
