### ISSUE TITLE
Talizman

### ISSUE THREAD

**Issue by venci666** [B1gLev/TryWillon#35]
le lehetett rakni és át alakult fejjé

**Comment by malacxd** [comment]
én is így vesztettem el az életerő talizmánom 
![kép](https://user-images.githubusercontent.com/75577033/101898345-40a68280-3bac-11eb-8ca1-a2e698c1f61f.png)

**Comment by B1gLev** [comment]
A mai napon javítani fogjuk. Köszönjük, hogy jeleztétek.

**Comment by malacxd** [comment]
Most missclickeltem, és megint lerakódott a talizmánom. (inventorymban van a fej)
