### ISSUE TITLE
Halál

### ISSUE THREAD

**Issue by Sleshie** [B1gLev/TryWillon#39]
A /k home kidobott a világból ezáltal oda az összes cuccom

Cuccom:
-fullos habszivacskard
-fullos szigony
-fullos netherite csákány
-netherite szett melles nélkül
-fullos elytra gyémántszintü védelem
A többit nemtom.

**Comment by malacxd** [comment]
Nekem is eltűnt pár cuccom szeró leállás miatt az ender chestemből
Ezek voltak:
1 netherite ásó pár enchanttal, 1 silk touchos pickaxe mendinggel, efi 3-mal és unbreaking 3-mal, tizenvalahány gyanús kavics, egy páncélozott netherite elytra (mending, prot 4, unb 3). a többire nem emlékszem

**Comment by TheKr1szTEN** [comment]
Az új szabályzat értelmében ilyen módon eltűnt felszerelést csak kép/log/videó felmutatása után tudunk vissza adni.
