### ISSUE TITLE
Elbuggolt cuccok

### ISSUE THREAD

**Issue by malacxd** [B1gLev/TryWillon#45]
Elbuggolt egy prot 8-as mendinges unbreaking 10-es netherite nadrág a slimefun auto disenchanterben.
beraktam mikor nem volt energia (-200 körül volt mert kifogytak a generátorok) és eltűnt a sima könyv meg a nadrág. nem tudtam mást berakni a disenchanterbe ezért kiütöttem és nem dobott semmit

**Comment by KingDeadZ** [comment]
Ez így működik az sfben, mellékesen azért nem engedett berakni a disenchanterbe disenchantolni mert már elindult a folyamat, hiába nem volt utána áramod

**Comment by malacmobile** [comment]
De utána elinditottam a generátort és nem történt semmi. Mondom a könyv és a nadrág eltűnt mert nem tudta elinditani, úgy érzékelte mintha el lenne indítva de nem volt, mert csak egy fekete üveg volt közepén.

**Comment by TheKr1szTEN** [comment]
Az SF hibákat nem tudjuk korrigálni. Amennyiben ilyen eszközt használsz, feltétlen csinálj előtte képet, ami tartalmazza a dátumot is.
