### ISSUE TITLE
Pet miatti kidobás. 

### ISSUE THREAD

**Issue by SzokeMartin** [B1gLev/TryWillon#46]
Harc közben más petjét megütöd kidob processing error vagy valami hasonló indokkal.

**Comment by malacxd** [comment]
(csak akkor dob ki ha karddal ütögeted, ha íjjal vagy pusztakézzel akkor nem)

**Comment by venci666** [comment]
(helyesbítenék: ha nem íjjal ölöd meg a petet akkor dob ki)

**Comment by TheKr1szTEN** [comment]
Jelenleg ideiglenesen kivettük a Pet plugint.
