### ISSUE TITLE
[Biglev/TryWillon]

### ISSUE THREAD

**Issue by PDF10** [B1gLev/TryWillon#49]
hali az egyik soulbound rune-ám elbuggolt miközben csináltam.  Tudsz tenni valamit? előre is kösz.

**Comment by TheKr1szTEN** [comment]
Ezt azért jobb lenne pontosítani, önhibából elveszett rúnákat nem adunk vissza.
Az új szabályzat értelmében érdemleges bizonyítás hiányában nem adunk vissza semmilyen elveszett, buggolt eszközt.
