### ISSUE TITLE
jelentés

### ISSUE THREAD

**Issue by PDF10** [B1gLev/TryWillon#51]
Azt szeretném elmondani hogy ahányszor csak nyitok egy kincsesládát és ritka pajzsot nyitok belőle nem kapom meg minden mást megkapok belőle, de a pajzsot egyszerüen sose kapom meg.

**Comment by B1gLev** [comment]
Még régebben a hírekbe írtuk, hogy egyes itemek nem fognak működni. És ez egy mmoitem pajzs ami jelenleg nincs bent a szerveren. Köszi hogy szóltál, el is felejtettem hogy abban a ládában az a pajzs mmoitem-bol van benne.

**Comment by PDF10** [comment]
egy ládának az árát legalább visszakaphatnám mert már vagy 6-jára történik ez? ha szabadna?

**Comment by B1gLev** [comment]
Persze vissza adom.
