### ISSUE TITLE
hello az alkímia szintezési szintje elvileg rosszul van leírva vagy hibás az alkímia rendszere

### ISSUE THREAD

**Issue by PDF10** [B1gLev/TryWillon#53]

**Comment by B1gLev** [comment]
Mi is a gond vele pontosan?

**Comment by PDF10** [comment]
az első szinten nem létezik az a vízlélegzete poti és gyorsaság főzete és az unalom főzete nem 250-es hanem 100 szintnél érhető el.

**Comment by B1gLev** [comment]
Feltételezem szinthez van kötve és azért.

**Comment by PDF10** [comment]
oké de elvileg rosszul van leírva github-on

**Comment by B1gLev** [comment]
Nálunk?

**Comment by PDF10** [comment]
igen

**Comment by B1gLev** [comment]
Lehet hogy rossz infó van kint. Javítom majd.
