### ISSUE TITLE
savsziget 

### ISSUE THREAD

**Issue by Zsozsoka** [B1gLev/TryWillon#7]
1 nem megy a biomchange és warm oceanon van igy nem spawnolnak az állatok
2 lehetne hogy az ércgenerátor generáljon netherkvarcot is ? 
endbe nincs mit kezdeni csak lootolsz oszt mész
a bolt kicsit fura növények nem kelenének ugyétem a fű stb

**Comment by B1gLev** [comment]
Javítva :)
