### ISSUE TITLE
Elveszett cuccok

### ISSUE THREAD

**Issue by Lacikahun145** [B1gLev/TryWillon#7]
/k home-oltam 2 blockon áltam volt az egyik felett 1 trapdoor és kizuhantam a világból.
Elveszett cuccaim amikre emlékszem: hűség 3 tör 3 önjav földelés tridentemre a full vas szett amiben nem volt sapka (eltörőben voltak) meg arra a kardra a emlékszem amit Kr1sztől kaptam meg 2 dia csákira de azokra az enchantokra amik rajtuk voltak nem emlékszem.

**Comment by TheKr1szTEN** [comment]
Intézve.
