### ISSUE TITLE
Kingdom turret "hátra maradt animáció,,

### ISSUE THREAD

**Issue by RayderHUN** [B1gLev/TryWillon#9]
Az inferno tornyot kiszedtem mikor egy játékost támadott, mert a játékos nem sebződött az inferno toronytól.
Sajnos az animáció az ott maradt. Eleinte ha elspawnoltam és vissza eltűnt, de mostanra örök.
![2020-08-06_01 48 25](https://user-images.githubusercontent.com/53087063/89474897-22a4bd80-d787-11ea-818b-d6be6a27f4cb.png)

Dartania ( kingdom ) 
Rayder

**Comment by TheKr1szTEN** [comment]
Ez a probléma a következő karbantartással meg fog oldódni, a hibajegyet lezárom.
